parameters:
#    pat_system.example.class: Pat\SystemBundle\Example

services:
#    pat_system.example:
#        class: %pat_system.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
